### ISSUE TITLE
Ajouter la capitainerie à devfriendlyplaces.net

### ISSUE THREAD

**Issue by wo0dyn** [shordeaux/capitainerie-coworking#20]
Le copain @avernois a lancé http://devfriendlyplaces.net/ pour regrouper les espaces sympas pour les développeurs :wink: 

La démarche pour créer `montauban.json` est décrite ici : 
https://github.com/avernois/devfriendlyplaces#contribute

**Comment by jocelyndubois** [comment]
C'est ajouté, en attente de merge.

**Comment by wo0dyn** [comment]
Cool. Thx.

**Comment by wo0dyn** [comment]
✔ Merged: avernois/devfriendlyplaces#64
